export type Country = { iso: string; en: string; ar: string; code: string; mask: string; len: number; starts?: string };

// From docs/index.html (COUNTRIES). Gulf first.
export const COUNTRIES: Country[] = [
  {iso: "SA", en: "Saudi Arabia", ar: "السعودية", code: "966", mask: "5X XXX XXXX", len: 9, starts: "5"},
  {iso: "AE", en: "United Arab Emirates", ar: "الإمارات", code: "971", mask: "5X XXX XXXX", len: 9, starts: "5"},
  {iso: "KW", en: "Kuwait", ar: "الكويت", code: "965", mask: "XXXX XXXX", len: 8},
  {iso: "BH", en: "Bahrain", ar: "البحرين", code: "973", mask: "XXXX XXXX", len: 8},
  {iso: "QA", en: "Qatar", ar: "قطر", code: "974", mask: "XXXX XXXX", len: 8},
  {iso: "OM", en: "Oman", ar: "عمان", code: "968", mask: "9XXX XXXX", len: 8},
  {iso: "IQ", en: "Iraq", ar: "العراق", code: "964", mask: "7XX XXX XXXX", len: 10},
  {iso: "JO", en: "Jordan", ar: "الأردن", code: "962", mask: "7X XXX XXXX", len: 9},
  {iso: "EG", en: "Egypt", ar: "مصر", code: "20", mask: "1X XXXX XXXX", len: 10},
  {iso: "LB", en: "Lebanon", ar: "لبنان", code: "961", mask: "XX XXX XXX", len: 8},
  {iso: "SY", en: "Syria", ar: "سوريا", code: "963", mask: "9XX XXX XXX", len: 9},
  {iso: "YE", en: "Yemen", ar: "اليمن", code: "967", mask: "7XX XXX XXX", len: 9},
  {iso: "PS", en: "Palestine", ar: "فلسطين", code: "970", mask: "5X XXX XXXX", len: 9},
  {iso: "SD", en: "Sudan", ar: "السودان", code: "249", mask: "9X XXX XXXX", len: 9},
  {iso: "LY", en: "Libya", ar: "ليبيا", code: "218", mask: "9X XXX XXXX", len: 9},
  {iso: "TN", en: "Tunisia", ar: "تونس", code: "216", mask: "XX XXX XXX", len: 8},
  {iso: "DZ", en: "Algeria", ar: "الجزائر", code: "213", mask: "5XX XX XX XX", len: 9},
  {iso: "MA", en: "Morocco", ar: "المغرب", code: "212", mask: "6XX XXX XXX", len: 9},
  {iso: "TR", en: "Turkey", ar: "تركيا", code: "90", mask: "5XX XXX XX XX", len: 10},
  {iso: "PK", en: "Pakistan", ar: "باكستان", code: "92", mask: "3XX XXX XXXX", len: 10},
  {iso: "IN", en: "India", ar: "الهند", code: "91", mask: "XXXXX XXXXX", len: 10},
  {iso: "BD", en: "Bangladesh", ar: "بنغلاديش", code: "880", mask: "1XXX XXX XXX", len: 10},
  {iso: "PH", en: "Philippines", ar: "الفلبين", code: "63", mask: "9XX XXX XXXX", len: 10},
  {iso: "ID", en: "Indonesia", ar: "إندونيسيا", code: "62", mask: "8XX XXXX XXXX", len: 11},
  {iso: "MY", en: "Malaysia", ar: "ماليزيا", code: "60", mask: "1X XXX XXXX", len: 9},
  {iso: "GB", en: "United Kingdom", ar: "المملكة المتحدة", code: "44", mask: "7XXX XXX XXX", len: 10},
  {iso: "US", en: "United States", ar: "الولايات المتحدة", code: "1", mask: "XXX XXX XXXX", len: 10},
  {iso: "CA", en: "Canada", ar: "كندا", code: "1", mask: "XXX XXX XXXX", len: 10},
  {iso: "DE", en: "Germany", ar: "ألمانيا", code: "49", mask: "15X XXXX XXXX", len: 11},
  {iso: "FR", en: "France", ar: "فرنسا", code: "33", mask: "6 XX XX XX XX", len: 9},
];
