"""Build supabase/seed/exercises.sql from Free Exercise DB + our common exercises.

Usage: python3 build_exercises.py <out.sql>
Free Exercise DB (public domain): https://github.com/yuhonas/free-exercise-db
Our common exercises (Arabic names, steps, machines): src/data/exercises.json
"""
import json, os, sys, urllib.request

COMMIT = 'f00c92c7dcf1216a928a52c3706c7ce8e2f71ed5'
RAW = f'https://raw.githubusercontent.com/yuhonas/free-exercise-db/{COMMIT}/dist/exercises.json'
IMG = f'https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@{COMMIT}/exercises/'
HERE = os.path.dirname(os.path.abspath(__file__))

fedb = json.load(urllib.request.urlopen(RAW))
ours = json.load(open(os.path.join(HERE, '..', '..', 'src', 'data', 'exercises.json')))

MUSCLE = {'chest': 'Chest', 'lats': 'Back', 'middle back': 'Back', 'lower back': 'Back', 'traps': 'Back',
          'shoulders': 'Shoulders', 'neck': 'Shoulders', 'biceps': 'Arms', 'triceps': 'Arms', 'forearms': 'Arms',
          'quadriceps': 'Legs', 'hamstrings': 'Legs', 'glutes': 'Legs', 'calves': 'Legs', 'adductors': 'Legs',
          'abductors': 'Legs', 'abdominals': 'Core'}
EQUIP = {'barbell': 'Barbell', 'e-z curl bar': 'Barbell', 'dumbbell': 'Dumbbell', 'machine': 'Machine',
         'cable': 'Cable', 'body only': 'Bodyweight', 'kettlebells': 'Free weight', 'medicine ball': 'Free weight'}

def q(v):
    if v is None: return 'null'
    if isinstance(v, bool): return 'true' if v else 'false'
    if isinstance(v, int): return str(v)
    return "'" + str(v).replace("'", "''") + "'"

def arr(xs):
    if xs is None: return 'null'
    return 'array[' + ','.join(q(x) for x in xs) + ']::text[]' if xs else "'{}'::text[]"

rows = []
by_id = {x['id']: x for x in fedb}
used = set()
for e in ours:
    f = by_id[e['fedb']]
    used.add(f['id'])
    search = ' '.join([e['en'].lower(), e['ar'], f['name'].lower()])
    rows.append([q(e['id']), q(e['en']), q(e['ar']), q(e['m']), arr(f['primaryMuscles']), q(e['t']), q(f.get('level')),
                 q(f.get('category')), arr(f['instructions']), arr(e.get('steps')), arr([IMG + i for i in f['images']]),
                 q(json.dumps(e['mach'], ensure_ascii=False)), q(bool(e.get('time'))), '0', q(search)])
for f in fedb:
    if f['id'] in used: continue
    m = MUSCLE.get((f['primaryMuscles'] or [''])[0], 'Other')
    t = EQUIP.get(f.get('equipment') or '', 'Other')
    rows.append([q(f['id']), q(f['name']), 'null', q(m), arr(f['primaryMuscles']), q(t), q(f.get('level')),
                 q(f.get('category')), arr(f['instructions']), 'null', arr([IMG + i for i in f['images']]),
                 'null', 'false', '1', q(f['name'].lower())])

cols = 'id, name_en, name_ar, muscle, muscles, equipment, level, category, steps_en, steps_ar, images, machines, timed, rank, search'
with open(sys.argv[1], 'w') as out:
    out.write('-- Generated by build_exercises.py. Do not edit by hand.\n')
    for i in range(0, len(rows), 150):
        out.write(f'insert into public.exercises ({cols}) values\n')
        out.write(',\n'.join('(' + ', '.join(r) + ')' for r in rows[i:i + 150]))
        out.write('\non conflict (id) do update set ' + ', '.join(f'{c} = excluded.{c}' for c in cols.split(', ')[1:]) + ';\n')
print(len(rows), 'exercises')
