"""Build supabase/seed/foods.sql from USDA SR Legacy + our curated lists.

Usage: python3 build_foods.py <sr.json made by usda_build> <out.sql>
sr.json: compact USDA SR Legacy list (pork, alcohol and baby food removed).
"""
import json, re, sys, os
sys.path.insert(0, os.path.dirname(__file__))
from basics import BASICS
from gulf import C, D

usda = {x['id']: x for x in json.load(open(sys.argv[1]))}
rows = []

def q(v):
    if v is None: return 'null'
    if isinstance(v, bool): return 'true' if v else 'false'
    if isinstance(v, (int, float)): return repr(round(v, 2))
    return "'" + str(v).replace("'", "''") + "'"

def slug(s): return re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-')

def add(id, source, category, name_en, name_ar, restaurant, s_en, s_ar, s_g, unit, k, p, c, f,
        sugar=None, fiber=None, sodium=None, parts=None, sugar_high=False, fat_high=False, est=False, rank=1, words=''):
    search = ' '.join(x for x in [name_en.lower(), (name_ar or ''), (restaurant or '').lower(), words.lower()] if x)
    rows.append([id, source, category, name_en, name_ar, restaurant, s_en, s_ar, s_g, unit, k, p, c, f,
                 sugar, fiber, sodium, json.dumps(parts, ensure_ascii=False) if parts else None,
                 sugar_high, fat_high, est, rank, search])

used = set()
for fid, en, ar, s_en, s_ar, g, words in BASICS:
    u = usda[fid]; used.add(fid)
    unit = 'ml' if re.search(r'\bml\b', s_en) else 'g'
    sugar_high = (u.get('sugar') or 0) * g / 100 >= 15
    fat_high = u['f'] * g / 100 >= 20
    add(f'usda:{fid}', 'usda', 'basic', en, ar, None, s_en, s_ar, g, unit, u['kcal'], u['p'], u['c'], u['f'],
        u.get('sugar'), u.get('fiber'), u.get('sodium'), None, sugar_high, fat_high, False, 0, words)

for en, ar, cat, rest, s_en, s_ar, kind, data, flags, words in D:
    if kind == 'parts':
        parts = []; tot = dict(g=0, k=0, p=0, c=0, f=0, s=0)
        for key, grams in data:
            n_en, n_ar, k, p, c, f, s = C[key]
            parts.append(dict(key=key, en=n_en, ar=n_ar, g=grams, k=k, p=p, c=c, f=f))
            tot['g'] += grams; tot['k'] += k * grams / 100; tot['p'] += p * grams / 100
            tot['c'] += c * grams / 100; tot['f'] += f * grams / 100; tot['s'] += s * grams / 100
        g = tot['g']; per = lambda v: v * 100 / g
        s_en = f"{s_en} ({g} g)"; s_ar = f"{s_ar} ({g} جم)"
        add(f'gymi:{slug(en)}', 'gymi', cat, en, ar, rest, s_en, s_ar, g, 'g', per(tot['k']), per(tot['p']), per(tot['c']), per(tot['f']),
            per(tot['s']), None, None, parts, 'sugar' in flags, 'fat' in flags, True, 0, words)
    else:
        k, p, c, f, s, g = data
        unit = 'ml' if re.search(r'\bml\b', s_en) else 'g'
        add(f'gymi:{slug(en)}', 'gymi', cat, en, ar, rest, s_en, s_ar, g, unit, k, p, c, f, s, None, None, None,
            'sugar' in flags, 'fat' in flags, True, 0, words)

for fid, u in usda.items():
    if fid in used: continue
    por = u.get('portion')
    s_en = f"{por[0]} ({por[1]:g} g)" if por else '100 g'
    g = por[1] if por else 100
    add(f'usda:{fid}', 'usda', 'usda', u['n'], None, None, s_en, None, g, 'g', u['kcal'], u['p'], u['c'], u['f'],
        u.get('sugar'), u.get('fiber'), u.get('sodium'), None, False, False, False, 1, '')

cols = 'id,source,category,name_en,name_ar,restaurant,serving_en,serving_ar,serving_g,unit,kcal_100,protein_100,carbs_100,fat_100,sugar_100,fiber_100,sodium_100,parts,sugar_high,fat_high,is_estimate,rank,search'
with open(sys.argv[2], 'w') as out:
    out.write('-- Generated by supabase/seed/build_foods.py. Do not edit by hand.\n')
    out.write('-- USDA FoodData Central (public domain) + Gymi estimates for Saudi and Gulf dishes.\n')
    for i in range(0, len(rows), 400):
        chunk = rows[i:i + 400]
        out.write(f'insert into public.foods ({cols}) values\n')
        out.write(',\n'.join('(' + ','.join(q(v) for v in r) + ')' for r in chunk))
        out.write(f'\non conflict (id) do update set {", ".join(f"{c}=excluded.{c}" for c in cols.split(",")[1:])};\n')
print(len(rows), 'foods written;', sum(1 for r in rows if r[21] == 0), 'featured')
